before_install:
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - sudo apt install -y python3-pip build-essential cmake default-jdk maven
  - git clone https://github.com/eclipse-cyclonedds/cyclonedds /tmp/cyclonedds
  - cd /tmp/cyclonedds && mkdir build && cd build && cmake ..  && make && sudo make install && cd $TRAVIS_BUILD_DIR
addons:
  apt:
    update: true

language: python3
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - travis_retry pip3 install tox
  - pip install codecov jsonpickle idl_parser
script:
  # - cd ../..
  - ./configure
  - python setup.py build
  - python setup.py bdist_wheel
  - pip install dist/python_cdds-0.1.0-py3-none-any.whl
  - tox
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov
